AllCops:
  NewCops: enable

  Exclude:
    - bin/*
    - config/initializers/*
    - db/migrate/*
    - db/schema.rb
    - lib/tasks/deployment/*
    - node_modules/**/*
    - vendor/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

require:
  - rubocop-rspec
  - rubocop-rails
