require("./active_nav");
require("./loader");
require("./modal");
require("./reload_after_submit");
require("./search");
require("./select_all_checkbox");
require("./slider");
require("./add_prescriptions");
require("./prescription_textarea.js");
